apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ml-engine.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ml-engine.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ml-engine.name" . }}
    spec:
      containers:
        - name: ml-engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30

          # © PUBLIUS33™ — PulseTrakAI™. All Rights Reserved.
