apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-engine.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ml-engine.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080

# © PUBLIUS33™ — PulseTrakAI™. All Rights Reserved.
