{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
  tls:
    - hosts: {{ .Values.ingress.hosts }}
      secretName: {{ include "frontend.fullname" . }}-tls
{{- end }}

# © PUBLIUS33™ — PulseTrakAI™. All Rights Reserved.
