apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsetrakai
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pulsetrakai
  template:
    metadata:
      labels:
        app: pulsetrakai
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
