apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-proxy.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "postgres-proxy.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6432

# © PUBLIUS33™ — PulseTrakAI™. All Rights Reserved.
